version: "2"
services:

  # rest-app:
  #   build: ./rest-app
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     PORT: 8080
  #   depends_on:
  #     - otel-collector
  #   volumes:
  #     - ./rest-app:/my-app
      
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.108.0
    command: ["--config=/etc/otel-collector-config.yaml", ""]
    volumes:
      - ./collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"
      - "55679:55679" # zpages extension

  prometheus:
    image: quay.io/prometheus/prometheus:v2.54.1
    command: 
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--storage.tsdb.retention.time=1h'
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--web.route-prefix=/'
      - '--enable-feature=exemplar-storage'
      - '--enable-feature=otlp-write-receiver'
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.1.1
    container_name: grafana
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"

  jaeger:
    image: jaegertracing/all-in-one:1.59
    container_name: jaeger
    command:
      - "--memory.max-traces=5000"
      - "--query.base-path=/jaeger/ui"
      - "--prometheus.server-url=http://prometheus"
      - "--prometheus.query.normalize-calls=true"
      - "--prometheus.query.normalize-duration=true"
    deploy:
      resources:
        limits:
          memory: 400M
    restart: unless-stopped
    ports:
      - "16686:16686"         # Jaeger UI
      - "4317"
    environment:
      - METRICS_STORAGE_TYPE=prometheus
      - COLLECTOR_OTLP_GRPC_HOST_PORT=jaeger:4317
  # opensearch:
  #   image: opensearchproject/opensearch:2.15.0
  #   container_name: opensearch
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1G
  #   restart: unless-stopped
  #   environment:
  #     - cluster.name=demo-cluster
  #     - node.name=demo-node
  #     - bootstrap.memory_lock=true
  #     - discovery.type=single-node
  #     - OPENSEARCH_JAVA_OPTS=-Xms300m -Xmx300m
  #     - DISABLE_INSTALL_DEMO_CONFIG=true
  #     - DISABLE_SECURITY_PLUGIN=true
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   ports:
  #     - "9200"