receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector
          scrape_interval: 5s
          static_configs:
            - targets: ['0.0.0.0:8888']

exporters:
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  # Data sources: metrics
  prometheus:
    endpoint: 0.0.0.0:8889
    # namespace: default

  # Data sources: metrics
  otlphttp/prometheus:
    endpoint: "http://prometheus:9090/api/v1/otlp"
    tls:
      insecure: true

  debug:
    # verbosity: detailed

  opensearch:
    logs_index: otel
    http:
      endpoint: "http://opensearch:9200"
      tls:
        insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [
        # otlphttp/prometheus,
        prometheus,
        # debug,
        # prometheusremotewrite
      ]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [
        # opensearch,
        debug
      ]

